-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object exposing (..)


type Todos_mutation_response
    = Todos_mutation_response


type Todos_row
    = Todos_row
