-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Todos_row exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Api.ScalarCodecs
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)

{-| 
-}
rowid : SelectionSet (Maybe Int) Api.Object.Todos_row
rowid =
      Object.selectionForField "(Maybe Int)" "rowid" [] (Decode.int |> Decode.nullable)


{-| 
-}
title : SelectionSet (Maybe String) Api.Object.Todos_row
title =
      Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


{-| 
-}
completed : SelectionSet (Maybe String) Api.Object.Todos_row
completed =
      Object.selectionForField "(Maybe String)" "completed" [] (Decode.string |> Decode.nullable)
